# @package _global_

# specify here default evaluation configuration
defaults:
  - _self_
  - datamodule: partia_text_bert
  - model: vcgsn
  - callbacks: null
  - logger: null
  - trainer: cpu
  - log_dir: evaluation.yaml

  - experiment: vcgsn/partial_bert

  # enable color logging
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

original_work_dir: ${hydra:runtime.cwd}

data_dir: ${original_work_dir}/data/

print_config: True

ignore_warnings: True

seed: null

name: "default"

# passing checkpoint path is necessary
ckpt_path: ???
